spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
        git:
          uri: https://github.com/JungleLu/PiggyMetricsConfig.git
          username: lujgyy@163.com
          password: ljg181517/*-
server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}